# Generated by Django 3.1.5 on 2021-02-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_job', models.CharField(max_length=250)),
                ('nex_job', models.CharField(max_length=250)),
                ('date_start_job', models.DateField()),
                ('date_end_job', models.DateField()),
            ],
        ),
    ]
