# Generated by Django 3.1.5 on 2021-02-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=400)),
                ('how_nuch', models.IntegerField(blank=True, null=True)),
                ('ed_izm', models.CharField(max_length=4, null=True)),
                ('sert_name', models.CharField(max_length=400, null=True)),
                ('sert_date_1', models.DateField(null=True)),
                ('sert_date_2', models.DateField(null=True)),
                ('sert_file', models.FileField(null=True, upload_to='')),
                ('sanp_name', models.CharField(max_length=400, null=True)),
                ('sanp_date_1', models.DateField(null=True)),
                ('sanp_date_2', models.DateField(null=True)),
                ('sanp_file', models.FileField(null=True, upload_to='')),
                ('passport_name', models.CharField(max_length=400, null=True)),
                ('passport_date', models.DateField(null=True)),
                ('passport_file', models.FileField(null=True, upload_to='')),
                ('pozhar_name', models.CharField(max_length=400, null=True)),
                ('pozhar_date_1', models.DateField(null=True)),
                ('pozhar_date_2', models.DateField(null=True)),
                ('pozhar_file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
