# Generated by Django 3.1.6 on 2021-02-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='file_schema',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
