# Generated by Django 3.1.6 on 2021-02-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organisatin', models.CharField(max_length=400)),
                ('rekvizity', models.CharField(max_length=400)),
                ('address_of_organistion', models.CharField(max_length=400)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
    ]
