# Generated by Django 3.1.6 on 2021-02-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='isp_schemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_schema', models.CharField(max_length=400)),
                ('date_schema', models.DateField()),
                ('file_schema', models.FileField(upload_to='')),
            ],
        ),
    ]
