# Generated by Django 3.1.6 on 2021-02-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='isp_schemas',
            new_name='isp',
        ),
        migrations.RenameField(
            model_name='isp',
            old_name='date_schema',
            new_name='date_isp',
        ),
        migrations.RenameField(
            model_name='isp',
            old_name='file_schema',
            new_name='file_isp',
        ),
        migrations.RenameField(
            model_name='isp',
            old_name='name_of_schema',
            new_name='name_of_isp',
        ),
    ]
